#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.local/bin/eww/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

# widgets not in use
# apps
# twitter
# volume
# fetch

## Open widgets 
run_eww() {
	${EWW} open-many \
            user \
            power \
            todo \
            control \
            date \
            calender \
            player \
            system \
            home \
            disk \
        downloads \
            config \
            pictures \
        documents \
            favourates 
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close-all 
	rm "$FILE"
fi
