#! /bin/sh

# - autostart
mpd -b &
picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst &
#xrandr --output --brightness 0.4 &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
#Esetxkbmap br

bspc config focus_follows_pointer true
bspc config border_width         3
bspc config focused_border_color '#b1e3ad'
bspc config normal_border_color '#3a434c'
# - variables
#alias bc='bspc config'
#alias br='bspc rule'

#Workspaces
bspc monitor -d 1 2 3 4 5 6

#Others
bc border_width 0
bc window_gap 10
bc split_ratio 0.52
bc borderless_monocle true
bc gapless_monocle true

#rules
#br -a Zathura state=tiled
